source $HOME/.config/nvim/config/airline.vim
source $HOME/.config/nvim/config/start-screen.vim
source $HOME/.config/nvim/config/plug.vim
source $HOME/.config/nvim/config/keymaps.vim
source $HOME/.config/nvim/config/settings.vim
source $HOME/.config/nvim/config/close-tag.vim
source $HOME/.config/nvim/config/lsp-config.vim
luafile $HOME/.config/nvim/config/compe-config.lua
luafile $HOME/.config/nvim/config/python-ls.lua
