
# shadow
shadow = false;
shadow-opacity = 0.25

# fade
fading = false;
fade-delta = 3.0;
fade-in-step = 0.03;
fade-out-step = 0.028;

# opacity
inactive-opacity = 1;
active-opacity = 1;
inactive-opacity-override = true;

# blur
blur-background = false;
blur-kern = "3x3box";

# backend
backend = "glx";
vsync = true;
unredir-if-possible = false;
detect-rounded-corners = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;

