exec-once = hyprpaper & waybar -c /home/relow/.config/waybar/config -s /home/relow/.config/waybar/style.css

source=~/.config/hypr/themes/mocha.conf


# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto

monitor=eDP-1,2520x1680@60,auto,auto


# Some default env vars.
env = XCURSOR_SIZE,24

input {
    kb_layout = pl
    repeat_rate = 45
    repeat_delay = 350
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = -0.1 
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

decoration {
    rounding = 10

#    blur = yes
#    blur_size = 4
#    blur_passes = 1
#    blur_new_optimizations = on

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = no
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = yes 
    preserve_split = yes 
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -1
}

misc {
    disable_hyprland_logo = true
}



$mainMod = SUPER

bind = $mainMod, return, exec, alacritty
bind = $mainMod, Q, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating, 

bind = $mainMod, P, exec, wofi --show drun
#bindr= $mainMod, P, exec, pkill wofi || wofi --show drun -i
bindr= $mainMod, B, exec, pkill waybar || waybar -c /home/relow/.config/waybar/config -s /home/relow/.config/waybar/style.css

# bind = $mainMod, R, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

bind = $mainMod, S, exec, grim

bind = $mainMod, F, fullscreen, 
bind = $mainMod, C, exec, /home/relow/.config/wofi/powermenu.sh

binde=, XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +1000
binde=, XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -1000
binde=, XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
binde=, XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle


binde=, XF86MonBrightnessUp, exec, light -A 1
binde=, XF86MonBrightnessDown, exec, light -U 1


# Move focus with mainMod and vim motion
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch workspaces with mainMod + [1-5]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [1-5]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
